version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - my_db_volume:/etc/mydb
volumes:
        my_db_volume:
            external: false
