version: "3"
services:
    db:
        container_name: mydb
        image: mysql:5.7
        ports:
            - "32001:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
        environment:
            - DISPLAY=127.0.0.1:0.0
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
